<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Search noginn.com</title>
    <link rel="stylesheet" href="style.css" type="text/css" media="screen" />
</head>
<body>
    <form action="<?php echo $this->url(); ?>" method="get">
        <input type="text" name="q" value="<?php echo $this->escape($this->query); ?>" />
        <input type="submit" value="Search" />
    </form>
    
<?php if ($this->webResults !== null): ?>
    <?php if (count($this->webResults) > 0): ?>
    <p>
        Showing <?php echo $this->webResults->getOffset() + 1; ?>-<?php echo $this->webResults->getOffset() + $this->webResults->count(); ?> 
        of <?php echo $this->webResults->getTotal(); ?> results
    </p>
    <ol id="web-results">
    <?php foreach ($this->webResults as $result): ?>
        <li>
            <h3><a href="<?php echo $result->getUrl(); ?>"><?php echo $result->getTitle(); ?></a></h3>
            <p class="description"><?php echo $result->getDescription(); ?></p>
            <p class="display-url"><?php echo $result->getDisplayUrl(); ?></p>
        </li>
    <?php endforeach; ?>
    </ul>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml', array('query' => $this->query)); ?>
    <?php else: ?>
    <p>We did not find any results for <strong><?php echo $this->escape($this->query); ?></strong></p>
    <?php endif; ?>
<?php endif; ?>
</body>
</html>